export default {
	CUSTOMER_GET_FETCHING : 'CUSTOMER_GET_FETCHING',
	CUSTOMERS_SET_FILTERS:'CUSTOMERS_SET_FILTERS',
	CUSTOMERS_SET_SORT:'CUSTOMERS_SET_SORT',
	CUSTOMERS_SET_PAGE:'CUSTOMERS_SET_PAGE',
	CUSTOMERS_SET_QUERY: 'CUSTOMERS_SET_QUERY',
	CUSTOMERS_GET_SUCCESS : 'CUSTOMERS_GET_SUCCESS',
	CUSTOMERS_GET_ERROR : 'CUSTOMERS_GET_ERROR',
	CUSTOMER_GET_SUCCESS : 'CUSTOMER_GET_SUCCESS',
	CUSTOMER_GET_ERROR : 'CUSTOME_GET_ERROR',
	CUSTOMER_PROPERTY_CHANGE : 'CUSTOMER_PROPERTY_CHANGE'
}