export default {
	CUSTOMER_GET_FETCHING : 'CUSTOMER_GET_FETCHING',
	CUSTOMERS_SORT_CHANGE:'CUSTOMERS_SORT_CHANGE',
	CUSTOMERS_PAGE_CHANGE:'CUSTOMERS_PAGE_CHANGE',
	CUSTOMERS_GET_SUCCESS : 'CUSTOMERS_GET_SUCCESS',
	CUSTOMERS_GET_ERROR : 'CUSTOMERS_GET_ERROR',
	CUSTOMER_GET_SUCCESS : 'CUSTOMER_GET_SUCCESS',
	CUSTOMER_GET_ERROR : 'CUSTOME_GET_ERROR',
	CUSTOMER_PROPERTY_CHANGE : 'CUSTOMER_PROPERTY_CHANGE'
}