export default {
	CUSTOMERS_GET : 'CUSTOMERS_GET',
	CUSTOMERS_GET_SUCCESS : 'CUSTOMERS_GET_SUCCESS',
	CUSTOMERS_GET_ERROR : 'CUSTOMERS_GET_ERROR',
	CUSTOMER_GET_SUCCESS : 'CUSTOMER_GET_SUCCESS',
	CUSTOMER_GET_ERROR : 'CUSTOME_GET_ERROR'
}